@startuml

!include use.ipuml

actor David as me

rectangle Elektrobit {
usecase "Androdid Application development" as AA
usecase "AOSP development" as AO
usecase "Software tests" as ST
usecase "Supervision of Students" as SoS
usecase "Client contact and support" as CC
}

me --> AA
me --> AO
me --> ST
me --> SoS
me --> CC

@enduml
